#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
#START=61

BIN=avahi-daemon
DEFAULT=/etc/default/$BIN
OPTIONS="-D"
RUN_D=/var/run/$BIN

start() {
    AVAHI_SERVICES_CONF_DIR=/tmp/avahi/services
    mkdir -p $AVAHI_SERVICES_CONF_DIR
    cp -f /usr/config/avahi/services/http.service $AVAHI_SERVICES_CONF_DIR/

	[ -f $DEFAULT ] && . $DEFAULT
	mkdir -p $RUN_D
    $BIN -f /etc/avahi/avahi-daemon.conf $OPTIONS
}

stop() {
  $BIN -k
}

reload() {
  $BIN -r
}

